Authentication
googleinterns/step136-2020 pull request #4
Opened 2020-07-01 09:00 UTC by Aliblas

Login and Logout servlets (and their respective javascript functions) don't work yet. For reasons I don't understand response.sendRedirect won't redirect despite valid links.

2020-07-01 13:06 UTC, isamitre requested changes

2020-07-01 13:06 UTC, isamitre commented on src/main/java/com/google/sps/servlets/LoginServlet.java
> +    // Request: param redirectUrl for after login is finished
the indentation should be two spaces, not a tab
[Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation)

2020-07-01 13:06 UTC, isamitre commented on src/main/java/com/google/sps/servlets/LoginServlet.java
> +import com.google.sps.util.UserHelper;
import statements should be alphabetical

2020-07-01 13:06 UTC, isamitre commented on src/main/java/com/google/sps/servlets/UserStatusServlet.java
> +import com.google.sps.util.UserHelper;
import statements should be alphabetical and in one block
[Java Style Guide](https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing)

2020-07-01 13:06 UTC, isamitre commented on src/main/java/com/google/sps/servlets/UserStatusServlet.java
> +    // Response: returns some user information JSON from the current user's sign-in API profile.
indentation should be two spaces

2020-07-01 13:06 UTC, isamitre commented on src/main/java/com/google/sps/util/UserHelper.java
> +    // returns: opaque String unique ID of the currently logged-in user.
indentation should be two spaces

2020-07-01 13:06 UTC, isamitre commented on src/main/webapp/javascript/UserAuth.js
> +    if (!redirectUrl) {
indentation should be two spaces
[JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#formatting-block-indentation)

2020-07-01 17:57 UTC, Aliblas commented
@googlebot I signed it!

2020-07-01 20:05 UTC, isamitre approved these changes

2020-07-01 20:05 UTC, isamitre commented on src/main/java/com/google/sps/servlets/LoginServlet.java
> +        String loginPageUrl = userService.createLoginURL(redirectUrl);
indentation should be two spaces

2020-07-01 20:05 UTC, isamitre commented on src/main/java/com/google/sps/servlets/UserStatusServlet.java
> +        System.out.println("User is logged in");
indentation should be two spaces and same goes for the else statement

2020-07-06 13:16 UTC, oturner24 approved these changes

2020-07-06 13:16 UTC, oturner24 commented on src/main/java/com/google/sps/servlets/LoginServlet.java
> +  public void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException {
nit: remove the space between doGet and (

2020-07-06 13:16 UTC, oturner24 commented on src/main/java/com/google/sps/servlets/LoginServlet.java
> +    return;
You can remove this - there's no need to explicitly return at the end of the method

2020-07-06 13:16 UTC, oturner24 commented on src/main/java/com/google/sps/servlets/UserStatusServlet.java
> +  public void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException {
nit: no space after method name

2020-07-06 16:54 UTC, merged